import { MagnifyingGlassIcon } from '@radix-ui/react-icons';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router';
import { useRealtimeStore } from '../lib/realtime-store';
import { searchTarget } from '../lib/search';
import { useAiMode } from '../lib/use-ai-mode';
import { Tag } from '../ui/Tag';
import { Breadcrumbs } from './Breadcrumbs';

export function TopBar() {
  return (
    <header className="flex h-12 shrink-0 items-center gap-4 border-b border-rule bg-paper px-4 min-[1360px]:px-6">
      <Breadcrumbs />
      <div className="ml-auto flex items-center gap-4">
        <GlobalSearch />
        <Connection />
        <AiModeTag />
        <Tag tone="warn" title="Every payment, order and case here is generated by the simulator.">
          SIMULATED DATA
        </Tag>
      </div>
    </header>
  );
}

function isTypingTarget(el: Element | null): boolean {
  if (!(el instanceof HTMLElement)) return false;
  return el.isContentEditable || ['INPUT', 'TEXTAREA', 'SELECT'].includes(el.tagName);
}

function GlobalSearch() {
  const ref = useRef<HTMLInputElement>(null);
  const [value, setValue] = useState('');
  const navigate = useNavigate();

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === '/' && !e.metaKey && !e.ctrlKey && !isTypingTarget(document.activeElement)) {
        e.preventDefault();
        ref.current?.focus();
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  const submit = (e: FormEvent) => {
    e.preventDefault();
    const to = searchTarget(value);
    if (!to) return;
    navigate(to);
    setValue('');
    ref.current?.blur();
  };

  return (
    <form role="search" onSubmit={submit} className="relative">
      <label htmlFor="global-search" className="sr-only">
        Search by payment, order or case id
      </label>
      <MagnifyingGlassIcon width={15} height={15} className="pointer-events-none absolute top-1/2 left-2 -translate-y-1/2 text-ink-2" />
      <input
        ref={ref}
        id="global-search"
        value={value}
        onChange={(e) => setValue(e.target.value)}
        onKeyDown={(e) => e.key === 'Escape' && e.currentTarget.blur()}
        placeholder="pay_, ord_ or PAY-0042"
        autoComplete="off"
        spellCheck={false}
        className="transition-color h-8 w-72 rounded-xs border border-rule bg-surface pr-8 pl-7 font-mono text-12 text-ink hover:border-rule-strong focus:border-rule-strong"
      />
      <kbd
        aria-hidden="true"
        className="pointer-events-none absolute top-1/2 right-2 grid h-5 w-5 -translate-y-1/2 place-items-center rounded-xs border border-rule bg-paper font-mono text-11 text-ink-2"
      >
        /
      </kbd>
    </form>
  );
}

const CONNECTION_LABEL = { connecting: 'Connecting', live: 'Live', reconnecting: 'Reconnecting' } as const;

function Connection() {
  const state = useRealtimeStore((s) => s.connection);
  return (
    <span
      role="status"
      title={state === 'live' ? 'Receiving case updates in real time' : 'Realtime updates paused. Data may be stale.'}
      className="inline-flex w-[104px] items-center justify-end gap-1.5 font-mono text-12 text-ink-2"
    >
      <span aria-hidden="true" className={state === 'live' ? 'size-1.5 bg-ok' : 'size-1.5 bg-warn'} />
      {CONNECTION_LABEL[state]}
    </span>
  );
}

/** Shows which AI mode the server runs in (docs/05 §10). Renders nothing until the health check answers. */
function AiModeTag() {
  const mode = useAiMode();
  if (!mode) return null;
  const title =
    mode === 'REPLAY'
      ? 'AI answers are replayed from recordings. No live model calls are made.'
      : mode === 'RECORD'
        ? 'Live model calls are made and recorded.'
        : 'Live model calls are made.';
  return (
    <Tag tone="neutral" title={title}>
      AI: {mode}
    </Tag>
  );
}
