/* Capture real UI segments plus explicitly illustrative title/architecture cards.
 * Requires an isolated, seeded REPLAY app at DEMO_URL and an OPS storageState file.
 * PLAYWRIGHT_MODULE can point to an existing Playwright installation.
 */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs');const path=require('node:path');
const work=process.env.DEMO_WORK||'/private/tmp/payops-video';const base=process.env.DEMO_URL||'http://localhost:5177';
const person=process.env.DEMO_NAME||'Shivam Govind Rao';const cardsOnly=process.env.DEMO_CARDS_ONLY==='1';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const card=(kicker,title,body,foot='PAYOPS AI  /  '+person.toUpperCase())=>`<!doctype html><style>*{box-sizing:border-box}body{margin:0;background:#F5F2EA;color:#202C28;font-family:Arial,sans-serif;padding:95px 110px}small{font-size:20px;letter-spacing:4px;color:#1E5A4C}h1{font-size:65px;line-height:1.1;letter-spacing:-2px;margin:32px 0 42px;max-width:1350px}p{font-size:29px;line-height:1.5;max-width:1120px;color:#52625A}.grid{display:flex;gap:24px;margin-top:40px}.box{padding:28px;border:1px solid #B8C3BB;flex:1;background:#FFFDF8;border-radius:8px;font-size:25px;line-height:1.6}.box b{color:#1E5A4C}.foot{position:absolute;bottom:60px;left:110px;right:110px;border-top:1px solid #B8C3BB;padding-top:20px;letter-spacing:2px;font-size:17px;color:#52625A}</style><small>${kicker}</small><h1>${title}</h1>${body}<div class="foot">${foot}</div>`;
const cards={
 intro:card('A PAYMENT OPERATIONS PROJECT','The payment succeeded.<br>The records disagree.','<p>Find the cause. Inspect the evidence.<br>Apply a permitted fix. Verify the outcome.</p><div class="grid"><div class="box">Gateway<br><b>CAPTURED</b></div><div class="box">Order<br><b>FAILED</b></div><div class="box">Ledger<br><b>MISSING</b></div></div>'),
 architecture:card('ARCHITECTURE · ILLUSTRATIVE WORKFLOW','Specialists investigate.<br>Code controls the action.','<p>Initial records → routing → selected specialists → grounded findings</p><div class="grid"><div class="box"><b>Payment</b><br>Gateway + order</div><div class="box"><b>Reconciliation</b><br>Ledger + settlement</div><div class="box"><b>Risk</b><br>Account + attempts</div></div><p>Proposal → policy → approval when required → executor → validator</p>','LANGGRAPH ORCHESTRATION  /  JEV DECISIONS  /  GEMINI INVESTIGATION'),
 engineering:card('IMPLEMENTATION','A complete path from<br>exception to checked outcome.','<div class="grid"><div class="box"><b>Workbench</b><br>React + TypeScript<br>Evidence and record inspection</div><div class="box"><b>Application</b><br>Node + Postgres<br>Jobs, approvals and audit</div><div class="box"><b>Agents</b><br>LangGraph + Jev + Gemini<br>Bounded investigation</div></div><p>Idempotent execution · durable state · independent verification</p>'),
 outro:card('PAYOPS AI · PROJECT WALKTHROUGH','Make the decision inspectable.<br>Make the outcome verifiable.','<p>Built by '+person+'.</p><p>Explore the code, architecture, evaluation reports,<br>and local setup in the GitHub repository.</p>','SIMULATED PAYMENTS  /  REPLAYED MODEL RESPONSES  /  ACTUAL APPLICATION EXECUTION')
};
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});const clipsFile=path.join(work,'clips.json');const cardIds=['intro','architecture','engineering','outro'];const clips=cardsOnly?JSON.parse(fs.readFileSync(clipsFile,'utf8')).filter(c=>!cardIds.includes(c.id)):[];async function capture(id,action,hold=10,auth='ops'){const ctx=await browser.newContext({viewport:{width:1600,height:900},storageState:path.join(work,auth+'.json'),recordVideo:{dir:path.join(work,'raw'),size:{width:1600,height:900}}});const page=await ctx.newPage();const epoch=Date.now();let start=0;const begin=()=>{start=(Date.now()-epoch)/1000};await action(page,ctx,begin);await sleep(hold*1000);const end=(Date.now()-epoch)/1000;await ctx.close();clips.push({id,file:await page.video().path(),start,end});fs.writeFileSync(path.join(work,'clips.json'),JSON.stringify(clips,null,2));console.log('captured',id,Math.round(end-start));}
for(const id of cardIds)await capture(id,async(p,c,begin)=>{await p.setContent(cards[id]);await sleep(300);begin()},3);
if(cardsOnly){await browser.close();return}
await capture('proof',async(p,c,begin)=>{await p.goto(base+'/cases/case_4ffcz5tnshvbn0');const finding=p.getByText('Webhook delivery for payment.captured failed after 3 attempts with HTTP status 500.',{exact:true});await finding.waitFor();await finding.scrollIntoViewIfNeeded();await sleep(800);begin();await sleep(3000);const section=p.locator('li').filter({has:p.getByRole('heading',{name:'Checked payment and gateway records',exact:true})});await section.getByRole('button',{name:'[ev_04]',exact:true}).click();await sleep(4000);console.log('proof', (await p.getByRole('dialog').innerText()).slice(0,400));},7);
await capture('resolution',async(p,c,begin)=>{await p.goto(base+'/cases/case_4ffcz5tnshvbn0');const action=p.getByRole('heading',{name:'Applied the action',exact:true});await action.waitFor();await action.scrollIntoViewIfNeeded();await sleep(600);begin();await sleep(6500);await p.getByRole('heading',{name:'Re-read the records and verified',exact:true}).scrollIntoViewIfNeeded();},10);
// Start a separate recorded refund case through the real user interface.
await capture('refund-wait',async(p,c,begin)=>{await p.goto(base+'/cases/case_xv765hfddd5zjj');await p.getByRole('button',{name:'Start investigation',exact:true}).waitFor();begin();await p.getByRole('button',{name:'Start investigation',exact:true}).click();let record;for(let i=0;i<60;i++){await sleep(500);record=await(await c.request.get(base+'/api/cases/case_xv765hfddd5zjj')).json();if(record.resolutionView?.pendingApprovalId)break;if(['RESOLVED','ESCALATED'].includes(record.status))throw Error('Refund did not pause: '+record.status)}if(!record.resolutionView?.pendingApprovalId)throw Error('No pending refund approval');fs.writeFileSync(path.join(work,'approval.json'),JSON.stringify({id:record.resolutionView.pendingApprovalId,caseId:record.id}));},3);
const auth=await browser.newContext();const response=await auth.request.post(base+'/api/auth/login',{data:{email:'manager@payops.dev',password:'payops-demo'}});if(!response.ok())throw Error('Manager login '+response.status());await auth.storageState({path:path.join(work,'manager.json')});await auth.close();
const approval=JSON.parse(fs.readFileSync(path.join(work,'approval.json')));
await capture('approval',async(p,c,begin)=>{await p.goto(base+'/approvals?approval='+approval.id);await p.getByRole('radio',{name:'Approve',exact:true}).waitFor();await sleep(600);begin();await sleep(5500);await p.getByRole('radio',{name:'Approve',exact:true}).check();await sleep(1500);await p.getByRole('button',{name:'Approve decision',exact:true}).click();await sleep(2500);await p.goto(base+'/cases/'+approval.caseId);for(let i=0;i<45;i++){const record=await(await c.request.get(base+'/api/cases/'+approval.caseId)).json();if(record.status==='RESOLVED')break;await sleep(500)}await p.reload();await p.getByRole('heading',{name:'Compare payment records',exact:true}).waitFor();console.log('approved refund');},8,'manager');
await capture('audit',async(p,c,begin)=>{await p.goto(base+'/audit?caseId='+approval.caseId);await p.getByRole('heading',{name:'Audit log',exact:true}).waitFor();await sleep(1800);begin();await sleep(3500);await p.mouse.wheel(0,320)},8);
await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
