import type { ReactNode } from 'react';
import { Link } from 'react-router';
import { GITHUB_URL } from './links';

/** Frame for the logged-out pages: one 72ch column on paper, wordmark on top, small footer. */
export function PublicLayout({ children }: { children: ReactNode }) {
  return (
    <div className="min-h-screen bg-paper text-ink">
      <a href="#main" className="sr-only focus:not-sr-only focus:absolute focus:top-2 focus:left-2 focus:bg-surface focus:px-3 focus:py-2">
        Skip to content
      </a>
      <header className="mx-auto flex h-12 max-w-[1040px] items-center justify-between px-4">
        <Link to="/" className="text-14 font-semibold tracking-[-0.005em] text-ink">
          PayOps <span className="font-normal text-ink-2">AI</span>
        </Link>
        <Link to="/login" className="link text-13">
          Sign in
        </Link>
      </header>
      <main id="main" className="mx-auto max-w-[1040px] px-4 pt-8 pb-16">
        {children}
      </main>
      <footer className="mx-auto max-w-[1040px] border-t border-rule px-4 py-6 text-12 text-ink-2">
        <p>Demo system. Every payment, order and case is generated by a simulator.</p>
        <nav aria-label="Legal" className="mt-2 flex gap-4">
          <Link to="/terms" className="link">
            Terms
          </Link>
          <Link to="/privacy" className="link">
            Privacy
          </Link>
          {GITHUB_URL ? (
            <a href={GITHUB_URL} className="link" rel="noreferrer">
              Source code
            </a>
          ) : null}
        </nav>
      </footer>
    </div>
  );
}
