import type { ReactNode } from 'react';
import { Link } from 'react-router';
import { linkButton } from './link-button';

/** Frame for the logged-out pages: wordmark and sign-in on top, a small footer with the legal pages. */
export function PublicLayout({ children, landing }: { children: ReactNode; landing?: boolean }) {
  return (
    <div className="min-h-screen bg-paper text-ink">
      <a href="#main" className="sr-only focus:not-sr-only focus:absolute focus:top-2 focus:left-2 focus:bg-surface focus:px-3 focus:py-2">
        Skip to content
      </a>
      <header className="mx-auto flex h-16 max-w-[1120px] items-center justify-between px-6 max-md:px-4">
        <Link to="/" className="text-16 font-semibold tracking-[-0.005em] text-ink">
          PayOps <span className="font-normal text-ink-2">AI</span>
        </Link>
        <nav aria-label="Account" className="flex items-center gap-5">
          <Link to="/login" className="link text-14">
            Sign in
          </Link>
          {landing ? (
            <Link to="/login" className={`${linkButton('primary')} h-9 px-4 text-14 max-sm:hidden`}>
              Open the demo
            </Link>
          ) : null}
        </nav>
      </header>
      <main id="main" className="mx-auto max-w-[1120px] px-6 pt-10 pb-8 max-md:px-4 max-md:pt-6">
        {children}
      </main>
      <footer className="mx-auto max-w-[1120px] border-t border-rule px-6 py-8 text-13 text-ink-2 max-md:px-4">
        <p>Demo system. Every payment, order and case is generated by a simulator.</p>
        <nav aria-label="Legal" className="mt-2 flex gap-4">
          <Link to="/terms" className="link">
            Terms
          </Link>
          <Link to="/privacy" className="link">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  );
}
