import { LegalPage } from './LegalPage';

export function TermsPage() {
  return (
    <LegalPage title="Terms" updated="29 September 2026">
      <section>
        <h2>This is a demonstration</h2>
        <p>
          PayOps AI is a portfolio project. It is not a payment service, does not connect to a real payment gateway, bank or merchant, and
          does not move real money.
        </p>
      </section>
      <section>
        <h2>All data is simulated</h2>
        <p>
          Every customer, payment, order, refund and case is generated by a built-in simulator. Names and email addresses are made up. Do not
          enter real personal, financial or card information anywhere in the app.
        </p>
      </section>
      <section>
        <h2>No guarantees</h2>
        <p>
          The software is provided as is, with no warranty. Results from the AI investigator, including diagnoses and proposed actions, are
          demonstration output and must not be used for real payment decisions. Demo data can be reset at any time.
        </p>
      </section>
      <section>
        <h2>Demo accounts</h2>
        <p>
          Sign-in uses shared demo accounts. Actions taken with them, such as approving a proposal, are recorded in the audit log like any
          other action.
        </p>
      </section>
    </LegalPage>
  );
}
